name: Publish Docker image
on: [push]

jobs:
  publish_bebone_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Bebone Docker image
      run: |
        docker build . --tag ghcr.io/Maksasj/bebone_docker:latest
        docker run ghcr.io/Maksasj/bebone_docker:latest
        docker push ghcr.io/Maksasj/bebone_docker:latest